// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmEjN6UvNHYyevt8pekOLS65L5xLiTFuQ',
    appId: '1:1074763221682:web:54450379c0465cc49857ab',
    messagingSenderId: '1074763221682',
    projectId: 'habit-2023',
    authDomain: 'habit-2023.firebaseapp.com',
    storageBucket: 'habit-2023.appspot.com',
    measurementId: 'G-74V9V478Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWl0IWq7k40B9MbfZakcL2mJ3gl8WS-WM',
    appId: '1:1074763221682:android:59ce51a012381efd9857ab',
    messagingSenderId: '1074763221682',
    projectId: 'habit-2023',
    storageBucket: 'habit-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACdBoSelkVBn8mwP70maYb2E7xsf4gr_8',
    appId: '1:1074763221682:ios:c7d0d13e465ca9c29857ab',
    messagingSenderId: '1074763221682',
    projectId: 'habit-2023',
    storageBucket: 'habit-2023.appspot.com',
    iosClientId: '1074763221682-b8i4t3t800d29behf4ot4eo21pmptu3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitApp2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACdBoSelkVBn8mwP70maYb2E7xsf4gr_8',
    appId: '1:1074763221682:ios:c7d0d13e465ca9c29857ab',
    messagingSenderId: '1074763221682',
    projectId: 'habit-2023',
    storageBucket: 'habit-2023.appspot.com',
    iosClientId: '1074763221682-b8i4t3t800d29behf4ot4eo21pmptu3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitApp2023',
  );
}
